# Generated by Django 3.1.6 on 2021-02-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
