# Generated by Django 3.1.6 on 2021-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210217_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pass_accuracy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
