# Generated by Django 3.1.6 on 2021-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_player_graph_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='graph_path',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
