# Generated by Django 3.1.6 on 2021-02-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210227_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamh2hfixtures',
            name='fixture_round',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
