# Generated by Django 3.1.6 on 2021-03-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210227_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamh2hstats',
            old_name='toal_graph_path',
            new_name='total_graph_path',
        ),
    ]
