# Generated by Django 3.1.6 on 2021-02-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210215_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
