# Generated by Django 3.1.6 on 2021-02-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210217_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='graph_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
