# Generated by Django 3.1.6 on 2021-02-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210224_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchquery', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=200)),
                ('image_path', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
                ('founded', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('venue_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamH2HFixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(blank=True, default=None, null=True)),
                ('id2', models.IntegerField(blank=True, default=None, null=True)),
                ('league', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('fixture_round', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('venue', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('home_logo', models.URLField(blank=True, default=None, null=True)),
                ('away_logo', models.URLField(blank=True, default=None, null=True)),
                ('score', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamH2HStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField(blank=True, default=None, null=True)),
                ('id2', models.IntegerField(blank=True, default=None, null=True)),
                ('total_games', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id1_games', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id1_games', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id1_wins', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id1_wins', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id1_draws', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id1_draws', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id1_losses', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id1_losses', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id1_goals_for', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id1_goals_against', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id1_goals_for', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id1_goals_against', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id2_games', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id2_games', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id2_wins', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id2_wins', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id2_draws', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id2_draws', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id2_losses', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id2_losses', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id2_goals_for', models.IntegerField(blank=True, default=None, null=True)),
                ('home_id2_goals_against', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id2_goals_for', models.IntegerField(blank=True, default=None, null=True)),
                ('away_id2_goals_against', models.IntegerField(blank=True, default=None, null=True)),
                ('id1_graph_path', models.URLField(blank=True, default=None, null=True)),
                ('id2_graph_path', models.URLField(blank=True, default=None, null=True)),
                ('toal_graph_path', models.URLField(blank=True, default=None, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
